name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: codeql-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with: { go-version-file: go.mod, cache: true }
      - run: go fmt ./...
      - run: go mod download
      - run: go mod verify
      - run: go mod tidy; git diff --exit-code go.mod
      - uses: dominikh/staticcheck-action@9716614d4101e79b4340dd97b10e54d68234e431 # 1.4.1
      - run: go test -race -v ./...
